### ISSUE TITLE
AKS Learn feedback: code typo for AKS trusted launch example

### ISSUE THREAD

**Issue by msfttklingenberg** [MicrosoftDocs/azure-aks-docs#117]
### Type of issue

Code doesn't work

### Feedback

The section for adding a nodepool that starts with - 
The following example deploys a node pool with vTPM enabled on a cluster named myAKSCluster with three nodes:

Has this command where a bad dash character is in use for the "cluster-name" flag. Copy and paste of the command does not work.

`az aks nodepool add --resource-group myResourceGroup -–cluster-name myAKSCluster --name mynodepool --node-count 3 --enable-vtpm`

Update command to the below:
`az aks nodepool add --resource-group myResourceGroup --cluster-name myAKSCluster --name mynodepool --node-count 3 --enable-vtpm  `

### Page URL

https://learn.microsoft.com/en-us/azure/aks/use-trusted-launch

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/use-trusted-launch.md

### Author

@schaffererin

### Document Id

62d7c1ae-b9a5-8555-a2f9-b7a0ef0ca8e9

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @msfttklingenberg! Good catch. Thanks so much for opening up this issue and bringing this to our attention. I just merged a [PR](https://github.com/MicrosoftDocs/azure-aks-docs-pr/pull/678) that fixes this typo. The changes will be live in the article soon. Since there's no further action needed here, I'm going to close out the issue. Thank you again!!

#please-close
