### ISSUE TITLE
AKS Learn feedback:

### ISSUE THREAD

**Issue by barnesyard** [MicrosoftDocs/azure-aks-docs#12]
### Type of issue

Outdated article

### Feedback

The article says to use a node size of D2s_v3 but that is not an option.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/learn/quick-kubernetes-deploy-portal?tabs=azure-cli

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/learn/quick-kubernetes-deploy-portal.md

### Author

@schaffererin

### Document Id

8ee5867f-c8ee-0ae9-a9fa-7cc10981f73f

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @barnesyard, thank you for your commitment to helping maintain quality AKS documentation!

The VM size in question, *D2s_v3*, is an option:
![ds2-v3](https://github.com/user-attachments/assets/050954d6-6043-4813-ad69-5a2f9325c560)

However, there were other aspects of this article that had outdated information, so I created a PR to address those. Since there's no action needed here, I'm going to close out this issue. Thanks again!

#please-close
