### ISSUE TITLE
AKS Learn feedback: Incurrect documentation in Kubernetes auth documentation

### ISSUE THREAD

**Issue by asdorsey** [MicrosoftDocs/azure-aks-docs#25]
### Type of issue

Outdated article

### Feedback

The "Enable Azure managed identity authentication for Kubernetes clusters with kubelogin" at https://learn.microsoft.com/en-us/azure/aks/enable-authentication-microsoft-entra-id#non-interactive-sign-in-with-kubelogin has incorrect information.

Under the "Non-interactive sign in with kubelogin" section, the note at the top of the section states "An optional query parameter format is included when getting clusterUser credential to overwrite the default behavior change. You can explicitly specify format to azure if you need to maintain the old kubeconfig format ."  However, when using the `--format azure` parameter, I receive an error "error: The azure auth plugin has been removed."

The documentation mentions that error, and states the fix is to use kubelogin, meaning the `--format azure` guidance given earlier is pointless and should be removed.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/enable-authentication-microsoft-entra-id#non-interactive-sign-in-with-kubelogin

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/enable-authentication-microsoft-entra-id.md

### Author

@schaffererin

### Document Id

407422c9-807a-e6b0-c820-ea8b19e55ed7

**Comment by schaffererin** [comment]
Hi, @asdorsey!

In the [Non-interactive sign-in with kubelogin](https://learn.microsoft.com/en-us/azure/aks/enable-authentication-microsoft-entra-id#non-interactive-sign-in-with-kubelogin) section, there's a callout stating that you should run the `kubelogin convert-kubeconfig` command if you receive the Azure auth plugin error.

Did you try running this command? I was able to run them successfully.

Since no updates are needed to the article, I'm going to close this GitHub issue.

Thanks! #please-close
