### ISSUE TITLE
AKS Learn feedback: Limitations for KMS etcd encryption to AKS need to be updated.

### ISSUE THREAD

**Issue by christianag54** [MicrosoftDocs/azure-aks-docs#30]
### Type of issue

Missing information

### Feedback

One of the limitations listed here 

https://learn.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption#limitations 
"If a cluster has KMS turned on, has a private key vault, it must use the API Server VNet integration tunnel. Konnectivity is not supported." 

This is missing a critical statement which used to be in a prior commit/version of that same doc which is "If a cluster has KMS turned on, has a private key vault, and isn't using the API Server VNet integration tunnel, **you can't stop and then start the cluster**." this specifically "can't stop and then start the cluster" needs to be added back since that hasn't changed and the stop operations isn't supported with that setup.

### Page URL

https://learn.microsoft.com/en-us/azure/aks/use-kms-etcd-encryption

### Content source URL

https://github.com/MicrosoftDocs/azure-aks-docs/blob/main/articles/aks/use-kms-etcd-encryption.md

### Author

@schaffererin

### Document Id

b5ec3a1e-88c2-8dcb-05f7-226a633718a1

**Comment by schaffererin** [comment]
#assign:schaffererin

**Comment by schaffererin** [comment]
Hi, @christianag54, thank you for your feedback! The limitation states that "if a cluster has KMS turned on and has a private key vault, it **must** use API Server VNet integration." This means that the previous statement that was removed is no longer valid. Since no updates are needed to the content, I'm going to close out the GitHub issue. Thanks again! #please-close
